Update .gitlab-ci.yaml

diff --git a/.gitlab-ci.yaml b/.gitlab-ci.yaml
--- a/.gitlab-ci.yaml
+++ b/.gitlab-ci.yaml
@@ -1,3 +1,6 @@
+if [ $? -ne 0 ] || echo "$ERROR_OUTPUT" | grep -qE '^(Msg|Error)'; then
+
+
 stages:
   - lint
  
